language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y xmount ewf-tools afflib-tools sleuthkit lvm2 mdadm cryptsetup libmagic1 avfs disktype squashfs-tools mtd-tools vmfs-tools
  - sudo modprobe fuse

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install coveralls
  - pip install python-magic
  - pip install humanize
  - pip install .

# Command to run tests, e.g. python setup.py test
script:
  - sudo coverage run test_imagemounter.py

# Report to coveralls
after_success:
  - coveralls
