sudo: yes
language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.wheels
    - PIP_FIND_LINKS=file://$PIP_WHEEL_DIR

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y xmount ewf-tools afflib-tools sleuthkit lvm2 mdadm cryptsetup libmagic1 avfs disktype squashfs-tools mtd-tools vmfs-tools
  - sudo modprobe fuse

install:
  - mkdir -p $PIP_WHEEL_DIR
  - pip wheel -r requirements.txt
  - pip wheel -r tests/requirements.txt codecov tox-travis

script:
  - tox

after_success:
  - codecov

cache:
  directories:
    - $HOME/.wheels
